cosmos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('allauth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('users/<int:pk>/', views.UserDetail.as_view(), name='users_detail'),
    path('users/<int:user_id>/follow/', views.user_follow, name='user_follow'),
    path('users/<int:user_id>/unfollow/', views.user_unfollow, name='user_unfollow'),
    path('users/update/', views.profile, name='users_update'),
    path('users/update/add_photo', views.add_profile_photo, name='add_profile_photo'),
    path('users/update/delete_photo', views.delete_profile_photo, name='delete_profile_photo'),
    path('events/', views.EventList.as_view(), name='events_list'),
    path('events/create/', views.EventCreate.as_view(), name='events_create'),
    path('events/<int:pk>/', views.EventDetail.as_view(), name='events_detail'),
    path('events/<int:event_id>', views.add_watchlist, name='events_watchlist'),
    path('events/<int:event_id>/remove', views.remove_watchlist, name='events_watchlistremove'),
    path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='events_update'),
    path('events/<int:event_id>/update/add_photo', views.add_event_photo, name='add_event_photo'),
    path('events/<int:event_id>/update/delete_photo', views.delete_event_photo, name='delete_event_photo'),
    path('parties/', views.PartyList.as_view(), name='parties_list'),
    path('parties/create/', views.PartyCreate.as_view(), name='parties_create'),
    path('parties/<int:pk>/', views.PartyDetail.as_view(), name='parties_detail'),
    path('parties/<int:pk>/update/', views.PartyUpdate.as_view(), name='parties_update'),
    path('parties/<int:viewingparty_id>/add_attendee/', views.add_attendee, name='parties_add_attendee'),
    path('parties/<int:viewingparty_id>/remove_attendee/', views.remove_attendee, name='parties_remove_attendee'),
    # path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='events_update'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

TYPES = (
    ('L', 'Lunar'),
    ('S', 'Solar'),
    ('C', 'Conjunction'),
    ('P', 'Planetary'),
    ('M', 'Meteor'),
    ('C', 'Comet'),
    ('AD', 'Asteroid'),
    ('AM', 'Astronomy'),
    ('SC', 'Spacecraft'),
)


class Event(models.Model):
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    event_type = models.CharField(
        max_length=20,
        choices=TYPES,
        default=TYPES[0][0],
    )
    start_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    start_time = models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    end_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    end_time = models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    best_date = models.DateField(auto_now=False, auto_now_add=False, null=True, blank=True)
    best_time = models.TimeField(auto_now=False, auto_now_add=False, null=True, blank=True)
    has_party = models.BooleanField(default=False)
    description = models.CharField(max_length=1200)
    users_watching = models.ManyToManyField(User, related_name='users_watching_event')
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='event_created_by_user')

    def __str__(self):
        return f"Event is {self.title} in {self.location}."

    def get_absolute_url(self):
        return reverse('events_detail', kwargs={'pk': self.id})

    @property
    def is_archived(self):
        return date.today() > self.end_date


class Profile(models.Model):
    photo_url = models.CharField(max_length=255, blank=True)
    birthdate = models.DateField(auto_now=False, auto_now_add=False, null=True)
    google_id = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    bio = models.CharField(max_length=500, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField(User, related_name='user_followers')

    def __str__(self):
        return f"This is the profile of {self.user}"


class ViewingParty(models.Model):
    name = models.CharField(max_length=100)
    party_location = models.CharField(max_length=100)
    start_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    start_time = models.TimeField(auto_now=False, auto_now_add=False, null=True)
    end_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    end_time = models.TimeField(auto_now=False, auto_now_add=False, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='party_created_by_user')
    description = models.CharField(max_length=500)
    attendees = models.ManyToManyField(User, related_name='party_attendees')
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='event_viewing_party')

    def __str__(self):
        return f"Viewing party is {self.name}."

    def get_absolute_url(self):
        return reverse('parties_detail', kwargs={'pk': self.id})


class Photo(models.Model):
    url = models.CharField(max_length=255)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True, blank=True)
    party = models.OneToOneField(ViewingParty, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f"Photo at {self.url}"

main_app/forms.py
# from multiprocessing import Event
from django import forms

from django.contrib.auth.models import User
from .models import Profile, Event

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

class UpdateProfileForm(forms.ModelForm):
    bio = forms.CharField(label='Bio', max_length=500, required=False)
    city = forms.CharField(label='City', max_length=50, required=False)
    birthdate = forms.DateField(label='Birthdate', required=False)

    class Meta:
        model = Profile
        fields = ['bio', 'city', 'birthdate']

class EventCreateForm(forms.ModelForm):

    def clean(self):
        cleaned_data = super(EventCreateForm, self).clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')

        if end_date <= start_date:
            raise forms.ValidationError("End date must be later than start date")

        return cleaned_data

    class Meta:
        model = Event
        fields = ['title', 'location', 'event_type', 'start_date', 'start_time', 'end_date', 'end_time', 'best_date', 'best_time', 'description']

main_app/views.py
from .models import Event, ViewingParty, Profile, Photo, User
from .forms import EventCreateForm, UpdateUserForm, UpdateProfileForm
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.functions import Lower
import uuid
import boto3
import requests
import json
import os
from dotenv import load_dotenv
# from django_property_filter import PropertyFilterSet


load_dotenv()


S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'cosmos-app'
NASA_API = str(os.getenv('NASA_API'))
MAPBOX_API = str(os.getenv('MAPBOX_API'))
# Create your views here.


def home(request):
    data = requests.get(f'https://api.nasa.gov/planetary/apod?api_key={NASA_API}').text
    converted_data = json.loads(data)
    url = converted_data['url']
    events = Event.objects.order_by('users_watching')[:6]
    parties = ViewingParty.objects.order_by('attendees')[:3]
    return render(request, 'home.html', {'url': url, 'events': events, 'parties': parties})


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(
            request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='profile')
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)
        user = User.objects.get(id=request.user.id)
        profile = Profile.objects.get(id=user.profile.id)

        try:
            photo = Photo.objects.get(profile=profile.id)

            return render(request, 'profile.html', {'user_form': user_form, 'profile_form': profile_form, 'photo_url': photo.url, 'photo': photo, 'profile': profile})
        except:
            return render(request, 'profile.html', {'user_form': user_form, 'profile_form': profile_form, 'photo': False})


class UserDetail(DetailView):
    model = User
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(UserDetail, self).get_context_data(**kwargs)
        context['events'] = Event.objects.filter(
            users_watching=self.get_object())
        context['parties'] = ViewingParty.objects.filter(
            attendees=self.get_object())
        context['profile'] = Profile.objects.get(user=self.get_object())
        try:
            profile = Profile.objects.get(user=self.get_object())
            context['photo'] = Photo.objects.get(profile=profile.id)
        except:
            context['photo'] = False
        return context


class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    fields = ['username', 'email', 'first_name', 'last_name']


def user_follow(request, user_id):
    follower = User.objects.get(id=request.user.id)
    user = User.objects.get(id=user_id)
    profile = Profile.objects.get(user=user_id)

    try:
        profile.followers.add(follower)
        next = request.POST.get('next', '/')
    except:
        print('error adding follower')

    return HttpResponseRedirect(next)


def user_unfollow(request, user_id):
    follower = User.objects.get(id=request.user.id)
    user = User.objects.get(id=user_id)
    profile = Profile.objects.get(user=user_id)
    print(follower, 'new function')
    print(user, 'new function')
    print(profile, 'new function')
    try:
        profile.followers.remove(follower)
        next = request.POST.get('next', '/')
    except:
        print('error removing follower')

    return HttpResponseRedirect(next)


class EventList(ListView):
    model = Event
    paginate_by = 50

    # class Meta:
    #     property_fields = ('is_archived', PropertyFilterSet, 'exact')

    def get_queryset(self):
        order = self.request.GET.get('orderby', 'start_date')
        # archived = self.request.GET.get('filter', 'is_archived')
        if order == 'name':
            new_context = Event.objects.order_by(Lower(order))
            # new_context = Event.objects.order_by(Lower(order)).filter(archived, Event.objects)
        else:
            new_context = Event.objects.order_by(order)
            # new_context = Event.objects.order_by(order).filter(archived, Event.objects)

        return new_context

    def get_context_data(self, **kwargs):
        context = super(EventList, self).get_context_data(**kwargs)
        context['orderby'] = self.request.GET.get('orderby', 'start_date')
        # context['archived'] = self.request.GET.get('filter', 'is_archived')
        return context


# class EventListFilterSet(PropertyFilterSet):
#     class Meta:
#         model = Event
#         fields = '__all__'
#         property_fields = ('is_archived', PropertyFilterSet, 'exact')


class EventDetail(DetailView):
    model = Event
    fields = ['title', 'location', 'event_type', 'start_date', 'start_time', 'end_date',
              'end_time', 'best_date', 'best_time', 'description', 'users_watching', 'created_by']

    def get_context_data(self, **kwargs):
        context = super(EventDetail, self).get_context_data(**kwargs)
        context['parties'] = ViewingParty.objects.filter(
            event=self.get_object())
        try:
            photo = Photo.objects.get(event=self.get_object())
            context['photo'] = photo
        except:
            context['photo'] = False
        return context


class EventCreate(LoginRequiredMixin, CreateView):
    form_class = EventCreateForm
    model = Event

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    fields = ['title', 'location', 'event_type', 'start_date', 'start_time',
              'end_date', 'end_time', 'best_date', 'best_time', 'description']

    def get_context_data(self, **kwargs):
        context = super(EventUpdate, self).get_context_data(**kwargs)
        try:
            event = Event.objects.get(id=self.get_object().id)
            photo = Photo.objects.get(event=event)
            if (photo.event == None):
                print('error no event found')
            else:
                context['photo'] = photo

        except:
            context['photo'] = False
        return context


class PartyList(ListView):
    model = ViewingParty
    paginate_by = 20

    def get_queryset(self):
        order = self.request.GET.get('orderby', 'start_date')
        if order == 'name':
            new_context = ViewingParty.objects.order_by(Lower(order))
        else:
            new_context = ViewingParty.objects.order_by(order)
        return new_context

    def get_context_data(self, **kwargs):
        context = super(PartyList, self).get_context_data(**kwargs)
        context['orderby'] = self.request.GET.get('orderby', 'start_date')
        context['mapbox_api'] = MAPBOX_API
        party_locations = ViewingParty.objects.all().values_list('party_location')
        geo_request_list = []
        for location in party_locations:
            geo_request = requests.get(
                'https://api.mapbox.com/geocoding/v5/mapbox.places/<str:location>.json')
            geo_request_list.append(geo_request)
        context['party_locations'] = geo_request_list
        return context


class PartyDetail(DetailView):
    model = ViewingParty
    fields = '__all__'


class PartyCreate(LoginRequiredMixin, CreateView):
    model = ViewingParty
    fields = ['name', 'party_location', 'start_date', 'start_time',
              'end_date', 'end_time', 'description', 'event']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PartyCreate, self).get_context_data(**kwargs)
        context['mapbox_api'] = MAPBOX_API
        return context


class PartyUpdate(LoginRequiredMixin, UpdateView):
    model = ViewingParty
    fields = ['name', 'party_location', 'start_date',
              'start_time', 'end_date', 'end_time', 'description']


def add_profile_photo(request):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]

        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # user = request.user
            profile = request.user.profile
            Photo.objects.create(url=url, profile=profile)

        except:

main_app/templates/main_app/event_form.html
{% extends 'base.html' %}


{% block content %}

<div class="container">

{% if object %}
<h1>Edit {{object.title}}</h1>
{% else %}
<h1>Add Cosmic Event</h1>
{% endif %}

{% if object %}
{% if photo.event.id == Null %}
<form action="{% url 'add_event_photo' event.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
	{% csrf_token %}
	<input type="file" name="photo-file">
	<br><br>
	<input type="submit" class="btn" value="Upload Event Photo">
</form>
{% else %}
<img src="{{ photo.url }}" class="responsive-img z-depth-2">
	<form action="{% url 'delete_event_photo' event.id %}" method="POST">
		{% csrf_token %}
	<input type="submit" class="btn" value="Delete Photo">
	</form>
{% endif %}
<!-- Leaving the action blank will use the same url that was used in order to get the form -->
<form action="{% url 'events_update' event.id %}" method="POST">
	{% csrf_token %}
	<table>
		<!-- <input type="text" id="id_start_time"> -->
		{{ form.as_table }}
	</table>

	<input type="submit" value="submit" class="btn" />
</form>

{% else %}

<form action="" method="POST">
	{% csrf_token %}
	<table>
		<!-- <input type="text" id="id_start_time"> -->
		{{ form.as_table }}

	</table>
	<input type="submit" value="submit" class="btn" />
</form>
{% endif %}

</div>
<script>
	const startDateEl = document.getElementById('id_start_date');
	M.Datepicker.init(startDateEl, {
		format: 'yyyy-mm-dd',
		defaultDate: new Date(),
		setDefaultDate: true,
		autoClose: true
	})

    const endDateEl = document.getElementById('id_end_date');
	M.Datepicker.init(endDateEl, {
		format: 'yyyy-mm-dd',
		defaultDate: new Date(),
		setDefaultDate: true,
		autoClose: true
	})

	const startTimeEl = document.getElementById('id_start_time');
	M.Timepicker.init(startTimeEl, {
		autoClose: true,
		twelveHour: false
	})

    const endTimeEl = document.getElementById('id_end_time');
	M.Timepicker.init(endTimeEl, {
		autoClose: true,
		twelveHour: false
	})


</script>

{% endblock content %}

main_app/templates/main_app/event_list.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row valign-wrapper">
    <div class="col s12 m8">
      <h1>Cosmic Events</h1>
    </div>
    <div class="col s12 m4 right-align">
      <a class="dropdown-trigger btn" href="#" data-target="filter-dropdown"><span class="material-icons" style="vertical-align:middle; margin-right: 5px;">sort</span>Sort</a>
      <ul id="filter-dropdown" class="dropdown-content">
        <li><a href="?orderby=title">By Name</a></li>
        <li><a href="?orderby=start_date">By Date</a></li>
        <li><a href="?orderby=event_type">By Event Type</a></li>
        <li><a href="?orderby=users_watching">By # of Watchers</a></li>
      </ul>
    </div>
  </div>
  <div class="row">
    {% for event in event_list %}
    <div class="col s12 m6 l4">
      <a href="{% url 'events_detail' event.id %}" style="color: black">
        <div class="card z-depth-2" {% if event.end_date and event.is_archived %} style="filter: grayscale(100%); background-color: #c3c3c3;" {% endif %}>
          <div class="card-image">
            {% if event.photo_set.all|length > 0 %} 
            {% for photo in event.photo_set.all %}
            <img
              src="{{ photo.url }}"
              height="200px"
              style="background-color: black; background-size: cover; object-fit: cover;"
            />
            {% endfor %} 
            {% else %}
            <img
              src="https://images.pexels.com/photos/4644812/pexels-photo-4644812.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
              height="200px"
              style="background-color: black; object-fit: cover;"
            />
            {% endif %}
            <div style="position: absolute; top: 10px; left: 10px;">
              <div class="chip" style="position: relative;">
                {{ event.event_type }}
              </div>
              {% if event.end_date and event.is_archived %}
              <div class="chip" style="position: relative;">
                Archived
              </div>
              {% endif %}
            </div>
            {% if user in event.users_watching.all %}
            <form
              method="POST"
              action="{% url 'events_watchlistremove' event.id %}"
            >
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}" />
              <button
                type="submit"
                onclick="M.toast({html: 'Event removed from watchlist.'})"
                class="btn-floating halfway-fab waves-effect waves-light red tooltipped"
                data-position="left"
                data-tooltip="Remove from Watchlist"
              >
                <i class="material-icons md-24">visibility_off</i>
              </button>
            </form>
            {% else %}
            <form method="POST" action="{% url 'events_watchlist' event.id %}">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}" />
              {% if event.end_date and event.is_archived %} 
              <button
                type="submit"
                onclick="M.toast({html: 'Event added to watchlist.'})"
                class="btn-floating halfway-fab waves-effect waves-light blue tooltipped"
                data-position="left"
                data-tooltip="Add to Watchlist"
              >
              {% else %}
              <button
                type="submit"
                onclick="M.toast({html: 'Event added to watchlist.'})"
                class="btn-floating pulse halfway-fab waves-effect waves-light blue tooltipped"
                data-position="left"
                data-tooltip="Add to Watchlist"
              >
              {% endif %}
                <i class="material-icons md-24">visibility</i>
              </button>
            </form>
            {% endif %}
          </div>
          <div class="card-content">
            <span class="card-title truncate">{{ event.title }}</span>
            <p class="truncate">
              <i class="tiny material-icons" style="margin-right: 5px">place</i>
              {{ event.location }}
            </p>
            <p class="truncate">
              <i class="tiny material-icons" style="margin-right: 5px">event</i>
              {{ event.start_date }} 
              {% if event.start_time %}
                @ {{ event.start_time }}
              {% endif %}
            </p>
            <p class="truncate">
              <i class="tiny material-icons" style="margin-right: 5px">visibility</i>
              {{ event.users_watching.all|length}} Watching
            </p>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>

  <!-- Pagination Snippet if event count surpasses 50 -->

  {% comment %}
  <div class="row pagination">
    <span class="col s12 step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
  {% endcomment %}
  <!-- End Pagination Snippet -->
</div>

{% endblock %}

main_app/templates/main_app/viewingparty_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">

    <h1>{{ viewingparty.name }} </h1>
    {% if user.is_authenticated %}
    {% if user in viewingparty.attendees.all %}
    <form method="post" action="{% url 'parties_remove_attendee' viewingparty.id %}">
        {% csrf_token %}
    <button class="btn">Unattend</button>
    </form>
    {% else %}
    <form method="post" action="{% url 'parties_add_attendee' viewingparty.id %}">
        {% csrf_token %}
    <button class="btn">Attend</button>
    </form>
    {% endif %}
    {% endif %}

    <p>Event: <a href="{% url 'events_detail' viewingparty.event.id %}">{{ viewingparty.event }}</a></p>
    <p>Description: {{ viewingparty.description }}</p>
    <p>Location: {{ viewingparty.party_location }}</p>
    <p>Start Date/Time: {{ viewingparty.start_date }} / {{ viewingparty.start_time }} </p>
    <p>End Date/Time: {{ viewingparty.end_date }} / {{ viewingparty.end_time }} </p>
    <p>Attendees: {{ viewingparty.attendees.all|length }}</p>
    <p>Created By: {{ viewingparty.user }}</p>

    <!-- add edit button below -->
    {% if user == viewingparty.user %}
    <div class="card-action">
        <a href="{% url 'parties_update' viewingparty.id %}">Edit</a>
    </div>
    {% endif %}

</div>

{% endblock %}

main_app/templates/main_app/viewingparty_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="row">
		{% if object %}
			<h1>Edit {{object.title}}</h1>
		{% else %}
			<h1>Create Viewing Party</h1>
		{% endif %}
	</div>
	<div class="row">
		<form action="" method="POST">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="fieldWrapper">
				{{ form.name.errors }}
				<label for="{{ form.name.id_for_label }}">Name:</label>
				{{ form.name }}
			</div>
			<div class="fieldWrapper">
				{{ form.party_location.errors }}
				<label for="{{ form.party_location.id_for_label }}">Party Location:</label>
				<mapbox-address-autofill access-token={{mapbox_api}}>			
					<input type="text" name="party_location" maxlength="100" required="" id="id_party_location" autocomplete="street-address">
				</mapbox-address-autofill>
			</div>
			<div class="fieldWrapper">
				{{ form.start_date.errors }}
				<label for="{{ form.start_date.id_for_label }}">Start Date:</label>
				{{ form.start_date }}
			</div>
			<div class="fieldWrapper">
				{{ form.start_time.errors }}
				<label for="{{ form.start_time.id_for_label }}">Start Time:</label>
				{{ form.start_time }}
			</div>
			<div class="fieldWrapper">
				{{ form.end_date.errors }}
				<label for="{{ form.end_date.id_for_label }}">End Date:</label>
				{{ form.end_date }}
			</div>
			<div class="fieldWrapper">
				{{ form.end_time.errors }}
				<label for="{{ form.end_time.id_for_label }}">End Time:</label>
				{{ form.end_time }}
			</div>
			<div class="fieldWrapper">
				{{ form.description.errors }}
				<label for="{{ form.description.id_for_label }}">Description:</label>
				{{ form.description }}
			</div>
			<div class="fieldWrapper">
				{{ form.event.errors }}
				<label for="{{ form.event.id_for_label }}">Event:</label>
				{{ form.event }}
			</div>
			<input type="submit" value="submit" class="btn" />
		</form>
	</div>
</div>

<script>
	const startDateEl = document.getElementById('id_start_date');
	M.Datepicker.init(startDateEl, {
		format: 'yyyy-mm-dd',
		defaultDate: new Date(),
		setDefaultDate: true,
		autoClose: true
	})
    const endDateEl = document.getElementById('id_end_date');
	M.Datepicker.init(endDateEl, {
		format: 'yyyy-mm-dd',
		defaultDate: new Date(),
		setDefaultDate: true,
		autoClose: true
	})
	const startTimeEl = document.getElementById('id_start_time');
	M.Timepicker.init(startTimeEl, {
		autoClose: true,
		twelveHour: false
	})
    const endTimeEl = document.getElementById('id_end_time');
	M.Timepicker.init(endTimeEl, {
		autoClose: true,
		twelveHour: false
	})
	const eventEl = document.getElementById('id_event');
	M.FormSelect.init(eventEl)
</script>

{% endblock content %}